### ISSUE TITLE
[FEATURE] Provide a simple employee profile that demonstrates the employee's strengths

### ISSUE THREAD

**Issue by gcctbilly** [COMP3122-2324-Project/Simpsyber#18]
To make a good choice, it is important to know the strengths and weaknesses of each employee (working time in this game). When I playing this game, because I do not know the general information of each employee, I have to click each task and click each employee to check whether one employee may make a greater contribution to the work.

I think it can provide a employee profile or some general tips to tell the player what each employee is good at. Then I can assign reasonable work to each employee. And this is more in line with the actual situation; the manager knows the strengths and weaknesses of each employee before assign them task.

For specific, the profile can add to top right of the employee card. just like the information button of the task. When user click the button it will pop up a table for profile of employee. for simplicity, it do not need the text information to introduce the employee, it just needs to sort the jobs working time (Design App < Design Database < Develop Database < QA App ...). By providing these information, it can help user to better do the choice and better game experience.

**Comment by EddyChan1129** [comment]
<img width="141" alt="image" src="https://github.com/COMP3122-2324-Project/Simpsyber/assets/156775927/dee3ffa0-8fd2-4e9a-9df5-acc48a774898">
Once you click DETAIL button, it will display the employee's features.
<img width="672" alt="截圖 2024-02-28 17 38 59" src="https://github.com/COMP3122-2324-Project/Simpsyber/assets/156775927/22eaff29-6626-4b19-bf95-21665cda81cf">

I believe the main problem is that the user interface didn't make it clear that there is a detail button, because the button is too small, haha.

**Comment by gcctbilly** [comment]
Oh, I did not notice it in the previous. Sorry.
